"""Add first_name and last_name to users

Revision ID: d87519865b36
Revises: f7593c8f8999
Create Date: 2024-08-21 01:50:39.548551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87519865b36'
down_revision = 'f7593c8f8999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('listing_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('platform')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=250), nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('last_name', sa.String(length=250), nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False, server_default='Unknown'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name', server_default=None)
        batch_op.alter_column('last_name', server_default=None)
        batch_op.alter_column('address', server_default=None)
    # ### end Alembic commands ###
    

def downgrade():
    # Drop the added columns in the downgrade
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # Add back the platform column in the listings table
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.VARCHAR(length=11), nullable=False))

    # Drop categories and listing_categories tables
    op.drop_table('listing_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
